version: "3.9"

services:
  kong-migration:
    image: kong:3.2.2-alpine
    command: "kong migrations bootstrap"
    networks:
      - hf42-network
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  hf42-network:
    name: hf42-network
    driver: bridge