version: "3.9"

services:
  kong-database:
    image: postgres:15-alpine
    container_name: kong-database
    hostname: kong-database
    restart: on-failure
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kong
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hf42-network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/kong

networks:
  hf42-network:
    name: hf42-network
    driver: bridge