version: "3.9"

services:
  display:
    extends:
      file: ../display/docker-compose.yml
      service: web

  detail:
    extends:
      file: ../detail/docker-compose.yml
      service: web

  home:
    depends_on: [ display, detail ]
    build: .
    ports:
      - "3002:3002"
    container_name: home-web-con
    hostname: home-web
    restart: no
    networks:
      - hf42-network

networks:
  hf42-network:
    name: hf42-network
    driver: bridge