version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: display-web-con
    hostname: display-web
    restart: no
    networks:
      - hf42-network

networks:
  hf42-network:
    name: hf42-network
    driver: bridge