version: "3.9"

services:
  api:
    build: .
    ports:
      - "7000:7000"
    container_name: order-service-api
    hostname: order-service
    restart: on-failure
    networks:
      - hf42-network

networks:
  hf42-network:
    name: hf42-network
    driver: bridge