version: "3.9"

services:
  api:
    build: .
    container_name: payment-service-api
    hostname: payment-service
    restart: on-failure
    networks:
      - hf42-network

networks:
  hf42-network:
    name: hf42-network
    driver: bridge
