// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: schema.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BookService_ValidateBooks_FullMethodName = "/schema.BookService/ValidateBooks"
)

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	ValidateBooks(ctx context.Context, in *ValidateBooksRequest, opts ...grpc.CallOption) (BookService_ValidateBooksClient, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) ValidateBooks(ctx context.Context, in *ValidateBooksRequest, opts ...grpc.CallOption) (BookService_ValidateBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[0], BookService_ValidateBooks_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceValidateBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookService_ValidateBooksClient interface {
	Recv() (*ValidateBooksResponse, error)
	grpc.ClientStream
}

type bookServiceValidateBooksClient struct {
	grpc.ClientStream
}

func (x *bookServiceValidateBooksClient) Recv() (*ValidateBooksResponse, error) {
	m := new(ValidateBooksResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	ValidateBooks(*ValidateBooksRequest, BookService_ValidateBooksServer) error
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) ValidateBooks(*ValidateBooksRequest, BookService_ValidateBooksServer) error {
	return status.Errorf(codes.Unimplemented, "method ValidateBooks not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_ValidateBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ValidateBooksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookServiceServer).ValidateBooks(m, &bookServiceValidateBooksServer{stream})
}

type BookService_ValidateBooksServer interface {
	Send(*ValidateBooksResponse) error
	grpc.ServerStream
}

type bookServiceValidateBooksServer struct {
	grpc.ServerStream
}

func (x *bookServiceValidateBooksServer) Send(m *ValidateBooksResponse) error {
	return x.ServerStream.SendMsg(m)
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schema.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ValidateBooks",
			Handler:       _BookService_ValidateBooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "schema.proto",
}
