version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "9000:9000"
    container_name: book-service-api
    hostname: book-service
    restart: on-failure
    networks:
      - hf42-network

networks:
  hf42-network:
    name: hf42-network
    driver: bridge