name: API unit tests

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Create env
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          cd book-service
          echo MONGO_URL="$MONGO_URL" > env/.env

      - name: Build
        run: |
          go build -v ./...

      - name: Test
        run: |
          GIN_MODE=release go test -v ./...