name: API unit tests

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./book-service

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.20

      - name: Install dependencies
        run: |
          go mod init main
          go mod tidy

      - name: Create env
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          echo MONGO_URL="$MONGO_URL" > env/.env

      - name: Build
        run: go build -v main.go

      - name: Test
        run: |
          cd controller
          GIN_MODE=release go test -v book_test.go