name: API unit tests

on:
  push:
    branches: [ main ]
    paths:
      - book-service/**
      - .github/workflows/book-test.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./book-service

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Create env
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: echo MONGO_URL="$MONGO_URL" > env/.env

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
          cache-dependency-path: book-service/go.sum

      - name: Install dependencies
        run: go mod download -x

      - name: Build
        run: go build -v main.go

      - name: Test
        run: GIN_MODE=release go test -v ./...