name: Order service API unit tests

on:
  push:
    branches: [ main ]
    paths:
      - order-service/**
      - .github/workflows/order-test.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order-service

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Create env
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
          RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
          RABBITMQ_EXCHANGE: ${{ secrets.RABBITMQ_EXCHANGE }}
          RABBITMQ_QUEUE: ${{ secrets.RABBITMQ_QUEUE }}
        run: |
          echo quarkus.mongodb.connection-string="$MONGO_URL" > .env
          echo RABBITMQ_HOST="$RABBITMQ_HOST" >> .env
          echo RABBITMQ_USERNAME="$RABBITMQ_USERNAME" >> .env
          echo RABBITMQ_PASSWORD="$RABBITMQ_PASSWORD" >> .env
          echo RABBITMQ_PORT="$RABBITMQ_PORT" >> .env
          echo RABBITMQ_EXCHANGE="$RABBITMQ_EXCHANGE" >> .env
          echo RABBITMQ_QUEUE="$RABBITMQ_QUEUE" >> .env

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: gradle build -x test

      - name: Run tests with Gradle Wrapper
        run: gradle test --stacktrace --debug
