name: Order service API unit tests

on:
  push:
    branches: [ main ]
    paths:
      - order-service/**
      - .github/workflows/order-test.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./order-service

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Create env
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: echo quarkus.mongodb.connection-string="$MONGO_URL" > .env

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: gradle build -x test

      - name: Run tests with Gradle Wrapper
        run: gradle test
